from typing import List

from pydantic import (
    BaseModel,
    Field,
)


class UserInput(BaseModel):
    """Schema for parsing user-provided account information."""

    identifier: str = Field(
        description="Identifier, which can be a customer ID, email, or phone number."
    )


class UserProfile(BaseModel):
    user_id: str = Field(description="The User ID of the customer")
    code: str = Field(description="The code generated by a Python coding agent")


class PythonLibrary(BaseModel):
    customer_id: str = Field(description="The customer ID of the customer")
    music_preferences: List[str] = Field(
        description="The music preferences of the customer"
    )
